### ISSUE TITLE
help with doing this project 

### ISSUE THREAD

**Issue by arunkumarmr** [ricardojoserf/ddos_simulation#1]
## Expected vs Actual Behavior
![Screenshot 2020-10-07 215101](https://user-images.githubusercontent.com/42640839/95358992-469b9100-08e7-11eb-9636-e4b01b3705b2.png)

please help me with reducing error,
and also please explain me about config.py file.

## Specifications

 - Operative system:

 - Version (e.g. Python version):

**Comment by ricardojoserf** [comment]
Hi @arunkumarmr . Thank you for noticing the bug. I think it is solved now, could you check if it works for you now?
The config.py file allows you to set the values that the program asks you, so you can execute it directly if you write the default values in config.py
Thank you for using the script and feel free to hit the start button if you like it ;)

Best regards,

Ricardo

**Comment by arunkumarmr** [comment]
Sir, I have to present my project presentation tommorow on Ddos .
Can you please share me sample inputs values ( IP ,threads,etc) or help me
in giving inputs .

**Comment by arunkumarmr** [comment]
Sir,I have doubts here,
1.Whose IP we have to consider?
2.what is number of IPs?
3.Number of message per IP?
4.what is that Interface?
5.what is IPs origin ?
 Expalin me about From ips.txt and Random choise.


Please guide/teach me as soon as possible.

**Comment by arunkumarmr** [comment]
im still getting error.

**Comment by ricardojoserf** [comment]
Hi arun,

IP to attack is the IP which will receive the traffic
Number of IPs is the number of random IP addressess to create
Number of messages per IP is the number of messages to create for every IP address you chose in the prvious option
The interface is what you chose, ens33 would work
IPs origin is to decide if the IPs will be the ones in ips.txt or random IP addresses generated by the program

If your interface is ens33 it should work with the inputs:

127.0.0.1
5
10
ens33
1
2

This would generate 50 packets from 5 different IPs, open Wireshark and you will see the packets

Test the latest update if you find any error please

Best regards,

Ricardo

**Comment by arunkumarmr** [comment]
When I checked in internet, I found that ens33 interface is for Linux , and
eth0 is for Windows.

Please provide a code which supports windows OS.

Thank you.

**Comment by ricardojoserf** [comment]
You can try this - https://stackoverflow.com/questions/40840400/on-windows-how-to-get-network-interface-name-whether-its-eth0-eth1-eth2-using-ba

Also, could you tell me what are you studying?

**Comment by arunkumarmr** [comment]
I'm a final year engineering ( b.tech ) student from India.

**Comment by arunkumarmr** [comment]
You have any simple Cyber security projects?
Help me if you have, please.

**Comment by ricardojoserf** [comment]
Hi arun,

This weekend I uploaded a script to attack ADFS (https://github.com/ricardojoserf/adfsbrute) and one to get the IP ranges of a company and the domains (https://github.com/ricardojoserf/ipv4info_scraper), those are very easy to understand.
Feel free to hit the "star" button this or any of those two projects if you like them ;) and good luck with your project!

**Comment by arunkumarmr** [comment]
Can you teach me how to crack my neighbours wifi , it will be always turned
on .
😁😂

**Comment by ricardojoserf** [comment]
For that you can check this one ;) - https://github.com/ricardojoserf/wifi-pentesting-guide

**Comment by arunkumarmr** [comment]
I think I should try all these projects on Linux OS .

**Comment by arunkumarmr** [comment]
That's so confusing.
Please help me doing this project for tommorow .
*Mobile Hotspot ( wifi ) hacking *
(WPA/WPA2 ENCRYPTED)

**Comment by arunkumarmr** [comment]
I do have only AMD 64 bit HP laptop with limited wifi.

**Comment by ricardojoserf** [comment]
Sorry arun, I can not help you. Good luck with the project anyway!
